version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: solaninadmin
      WORDPRESS_DB_PASSWORD: "123456"
      WORDPRESS_DB_NAME: "solanin"
    volumes:
      - ./wordpress/:/var/www/html

  db:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_PORT: 3306
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: solanin
      MYSQL_USER: solaninadmin
      MYSQL_PASSWORD: "123456"
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./mysql/:/var/lib/mysql

volumes:
  wordpress:
  db:
